name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
          destination_dir: ${{ github.sha }}

      - name: Create comment with report link or log URL
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reportUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/${context.sha}`;
            const message = `Playwright Test Report available at: ${reportUrl}`;

            if (context.eventName === 'pull_request') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            } else {
              console.log(message);
            }
      - name: Cleanup old reports
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { data: branch } = await github.rest.repos.getBranch({
              owner,
              repo,
              branch: 'gh-pages',
            });
            const { data: tree } = await github.rest.git.getTree({
              owner,
              repo,
              tree_sha: branch.commit.sha,
              recursive: 'true'
            });
            const now = new Date();
            const oldReports = tree.tree
              .filter(item => item.type === 'tree' && /^[a-f0-9]{40}$/.test(item.path))
              .filter(item => {
                const reportDate = new Date(item.path.substring(0, 10));
                const daysDiff = (now - reportDate) / (1000 * 60 * 60 * 24);
                return daysDiff > 30;
              })
              .map(item => item.path);
            if (oldReports.length > 0) {
              await github.rest.repos.createOrUpdateFileContents({
                owner,
                repo,
                path: '.cleanup',
                message: 'Cleanup old reports',
                content: Buffer.from(oldReports.join('\n')).toString('base64'),
                branch: 'gh-pages',
              });
            }
